### PR TITLE
Create bucket in default region if it doesnt exist

### PR DESCRIPTION
**Pull request by justinmchase**
If the bucket doesn't exist already, create it.

### CODE REVIEW

**Comment by jacobheun** [comment]
I think this would be good to be configurable as people may not want to inadvertently create Buckets. Perhaps taking from the datastore-fs logic and using `createIfMissing`:

```js
const store = new S3Store('.ipfs/datastore', {
  s3: s3Instance,
  createIfMissing: false  // defaults to true (mimic datastore-fs)
})
```

Also, it might be good to put the logic in `open` and not `put` since it's only needed when the repo starts.

**Comment by justinmchase** [comment]
Yeah, sounds good. I'll add that tonight.

**Comment by justinmchase** [comment]
I added tests and documentation and manually tested locally.

**Comment by jacobheun** [comment]
LGTM!

**Pull request merged**
